gliderlabs/registrator

Godeps/Godeps.json, Godeps/_workspace/src/github.com/docker/docker/pkg/units/MAINTAINERS, Godeps/_workspace/src/github.com/docker/docker/pkg/units/duration.go, Godeps/_workspace/src/github.com/docker/docker/pkg/units/duration_test.go, Godeps/_workspace/src/github.com/docker/docker/pkg/units/size.go, Godeps/_workspace/src/github.com/docker/docker/pkg/units/size_test.go
Follow-on from #84. Godep is kind of a turd.  This wasn't picked up because the dependency
wasn't imported on Darwin, only (?) on Linux.
=> Add missing github.com/docker/docker/pkg/units dep

consul.go, etcd.go, skydns2.go
Added error logging to etcd/consul/skydns2 backends so errors are logged to the console while retrying the backend. This helps to show backend problems rather than silently retrying forever.
=> Storage backend error logging.

bridge.go, registrator.go
Adds a call to `bridge.Remove()` when a container is stopped.
=> Remove service on container stop event

registrator.go
In the discussion of #94 it is speculated that just a new build is required as the problem was corrected in an upstream dependency. I came across centurylink/golang-builder, a Docker image for building Go executables and packaging them into a Docker container. The canonical import path needed to be added to the main package in order for it successfully compile and build.
=> Added canonical import path to main package.

README.md, bridge.go
Containers started with --net=host were not discovered by registrator because their NetworkSettings.Ports section is empty. The corresponding information is however present in HostConfig.PortBindings for containers started using net=host.
This patch adds optional support for HostConfig.PortBindings, but defaults to the configuration in NetworkSettings.Ports to ensure backwards compatibility.
=> Added discovery for services running with --net=host.

consul.go
This PR is work in progress and depends on unreleased Consul features (available in master branch) and the hashicorp/consul#627 pull request to add address support to the consul go api.
=> Use the service Address field of Consul 0.5.0 RC1+

registrator.go
Fixes error running “go get -u github.com/gliderlabs/registrator” due
to the import check.
=> Fix import comment for move to "gliderlabs"

bridge/bridge.go, bridge/types.go, registrator.go
Provides a fix for #82.
This only deregisters containers that:
* exited cleanly with status "0"
* shutdown with docker "stop" or "kill"
Otherwise the container is assumed to have exited unexpectedly. It is
left in the service registry so that health checks can detect that the
container failed.
When a container dies with a non-zero exit, but a refresh TTL is set, the service is immediately removed from the list to refresh, but not deregistered. However, it needs to retain the list of Service objects in case the "die" event is followed by a "stop" or "kill" event, and can then be deregistered. So, the info is moved to  "deadContainers" map, which will be removed if the TTL is reached without another either being deregistered or restarted.
=> Only deregister containers cleanly shutdown

CHANGELOG.md, README.md, consul/consul.go
Similar to the request in #58, this patch adds the interpolation of
service IPs and ports for Consul's SERVICE_CHECK_SCRIPT using the
placeholders, SERVICE_PORT and SERVICE_IP:
SERVICE_CHECK_SCRIPT=nc $SERVICE_IP $SERVICE_PORT | grep OK
To keep things simple, each check is specific only to the service in
question; specifically, the check does not have a full view of the
container and all of its ports.
=> Interpolate Consul service health checks.

etcd/etcd.go
etcd & client instead of the etcd2 object and client2 objects were being used read from the server.  This caused a panic making the use of registrator against an etcd2 backend impossible.
=> Fix bug in etcd backend when connecting to etcd2

README.md, bridge/bridge.go, bridge/util.go
This PR adds support for Docker 1.6 labels to use those instead of environment variables for for service metadata.
=> Using labels instead of environment variables to define metadata

CHANGELOG.md, README.md, consul/consul.go
This also adds support for HTTP check timeout
The benefits of this change are: removed dependency on check-http and much better behaviour when faced with unresponsive HTTP server (check-http would take tens of seconds, if not minutes, to timeout).
It is my understanding that this function would affect GH #156 (https://github.com/gliderlabs/registrator/issues/156#issuecomment-94525221) and GH #172.
=> Consul: Use native HTTP checks instead of check-http wrapper

Makefile, bridge/util.go
Hi :)
This PR is a patch for the crash outlined at https://github.com/gliderlabs/registrator/issues/226
> The cause of the crash is when the protocol from the HostPort portion is omitted in the API call (which the API is OK with.. it must default to TCP?)
I also added a Makefile tweak for the dev section to support more rapid dev testing (whilst maintaining the existing default), e.g:
`DEV_RUN_OPTS="-internal consul://consul.docker:8500" make dev`
=> Missing protocol fix

registrator.go
Checks for new versions with the "usage" service and automatically displays a
standard version message when the "--version" flag is passed.
This is an example of how we could use the Checker interface I added to the usage package to automatically handle the "--version" flag to provide a nice version message with information on when the version is out of date.
=> Add new version checker

CHANGELOG.md, bridge/bridge.go, bridge/bridge_test.go, bridge/types_test.go, registrator.go
- bridge.New no longer attempts to ping an adapter, caller must now use the bridge Ping method
- a few simple tests have been added to the bridge pkg
=> Refactor bridge for better testability

etcd/etcd.go
In our system, we've been seeing issues where, when etcd becomes unreachable to registrator, it needs to be kicked manually to publish its local service entries to etcd again. We believe that by using etcd client's SyncCluster functionality, we can synchronize the set of etcd servers with registrator and avoid this situation. Our proposal is that a client should initially use the local proxy, then via a proxied request, it discovers the current cluster topology. That topology is subsequently used directly, and the proxy is no longer used. We think this will buy us better retry behavior against etcd servers.
=> Synchornize etcd cluster in registrator on service registration

registrator.go
Go's "flag" module only parses options up until the first non-option argument,
so additional arguments are left unparsed in "flag.Args()". We only expect one
argument, but additional arguments were ignored, leading to some confusion
about options that were ignored.
This updates the Usage() message with the syntax showing the options before the
registry URI, as well as more detail if the registry argument is missing, or
additional arguments are found.
Fixes #288
=> Add more detailed usage regarding options placement

bridge/util.go
When using the Docker multi-host networking, IPAddress under NetworkSettings is set to an empty string and the container IP can be retrieved from NetworkSettings.Networks.
At this point it is assumed a single Docker network is associated with the container
=> Support for Docker multi host networking

consul/consul.go, consulkv/consulkv.go, docs/user/backends.md
This PR adds support for socket-based Consul connections. This would be especially convenient in overlay network environments where it could be difficult to tell whether you're talking to the _local_ Consul node or a remote one. It'd also be useful in Docker-in-Docker use cases like RancherOS where you may want to run Registrator in `system-docker` so that it's available immediately on boot. 
I piggy-backed onto the existing `consul` and `consulkv` Factories by adding a `-unix` suffix to the schemes and then doing a little additional parsing in `New()`.
The service backend works as expected, but the KV backend looks a little funky. Since we can't rely on slashes for the path (and thus the KV prefix), there's an extra colon to delimit the prefix i.e. …
=> Add support for Consul unix sockets

bridge/bridge.go, registrator.go
Instead of using the "kill" and "stop" events, this uses the exit status to
check whether the container was terminated via a signal. This will be more
reliable since the "kill" event can also be sent for non-fatal signals such as
SIGHUP.
Fixes #248
=> Use exit status to determine if container was killed

bridge/util.go
add support hostip for overlay network
=> Fix missing ServiceAddress when using networks from docker-compose (overlay)

docs/user/backends.md, etcd/etcd.go
Most people would be running etcd2 now and the default port is 2379 not 4001.
Therefore I've changed it to reflect the default that etcd2 provides.
=> Default etcd backend port to 2379

consul/consul.go, docs/user/backends.md
Adds a Consul TCP health check by specifying ..._CHECK_TCP=true
issue #225
=> added Consul TCP Health Check

consul/consul.go, docs/user/backends.md
- Adding a `consul-tls` backend scheme. It means that you want to use a CA file, CERT file, and KEY file to access consul TLS backend.
- Run registrator the following way:
```
docker run -d --name=registrator --net=host  -v /var/run/docker.sock:/tmp/docker.sock -v /etc/certificates/:/etc/certificates/ -e CONSUL_CACERT=/etc/certificates/docker-ca.crt -e CONSUL_TLSCERT=/etc/certificates/consul-client.crt -e CONSUL_TLSKEY=/etc/certificates/consul-client.key cyprien/registrator consul-tls://srv-consul.local:8543
```
=> adding TLS support for consul backend

bridge/bridge.go
This PR removes `stale` services from the registrator's memory. A `stale` service is a service that is present in the memory but its corresponding container is not actually running on the host (or has exited).
This issue has been observed when registrator at times misses out on capturing some docker *(die)* events. Hence this could lead to stale services which also get propagated into the registry backends.
My solution here is to add logic during cleanup to check whether the services in memory actually have their corresponding container running on the host. If not, then remove it.
I have tested this on my end and it seems to work just fine!
Relates to: https://github.com/gliderlabs/registrator/issues/325
=> Remove stale services from registrator

consul/consul.go, docs/user/backends.md
This allows to specify initial consul health check status:
`docker run -e "SERVICE_CHECK_INITIAL_STATUS=passing" image`
I know this is a duplicate of #343, but I need this ASAP.
=> Add consul initial check status to service attributes

bridge/bridge.go
Simple change to support the fact that docker no longer fills out mapped ports when run in --net=host mode. This instead simply reads all exposed ports and fills out the relevant service structure, restoring the original functionality.
Fixes #159
=> Use ExposedPorts for --net=host

bridge/bridge.go, bridge/types.go, docs/user/run.md, registrator.go
These changes introduce the ability to use an IP address for registration of a container in Consul (or any other supported backend), which is stored in a label assigned to a Docker container.
This is especially useful when orchestrating containers in a cluster environment with different private network ranges, like e.g. [Rancher](http://rancher.com/).
See also the discussion at #454 for details.
=> Adds 'useIpFromLabel' parameter

bridge/bridge.go
Kubernetes pods create a single container which holds the IP for all other containers in the pod. Thus, when using Registrator, services could appear without an IP address. This PR solves that issue by detecting the namespace is shared, and extracting the IP information from the container holding it.
=> Grab IP from containers sharing network namespace

bridge/types_test.go, bridge/util.go, bridge/util_test.go, docs/user/services.md
#390
Example: 
```
docker run -d \
-p 4242:4242 \
-e 'SERVICE_4242_TAGS=traefik.frontend.rule=Host: www.example.com\, Path: /api,traefik.enable=true' \
company/service
```
Create only 2 tags into consul:
- `traefik.frontend.rule=Host: www.example.com, Path: /api`
- `traefik.enable=true`
=> feat(consul,service_tags): Support escaped comma

Dockerfile, Dockerfile.dev
A simple change to add the ca-certificates package back in following the upgrade to alpine 3.5.
This package is no longer installed along with the go apk package, so HTTPS requests are failing inside registrator.  It may fix some issues users have been seeing, if they were using a valid certificate.  (e.g. https://github.com/gliderlabs/registrator/issues/516)
=> Fix missing ca-certificates package in alpine 3.5

consul/consul.go
This code allows to specify DeregisterCriticalServiceAfter interval for consul 0.7.0+ via environment variable SERVICE_*_CHECK_DEREGISTER_AFTER
=> Added support for DeregisterCriticalServiceAfter

consul/consul.go
If you use the flag "-internal" is substituted not a valid port to $SERVICE_CHECK_SCRIPT.
Please view and accept the changes, they solve this problem.
> SERVICE_CHECK_SCRIPT=nc $SERVICE_IP $SERVICE_PORT | grep OK
=> fix service ip and port in consul interpolateService

bridge/bridge.go, bridge/types.go, registrator.go
This adds the option "-explicit" which makes registrator ignore all
services which don't have a SERVICE_NAME label.
=> Add option to only register services which have SERVICE_NAME

docs/user/backends.md, docs/user/services.md
I had trouble finding a list of the available `SERVICE_CHECK_*` environment variables, so I added a link from where I expected them to be. I also added a check parameter that was missing from the docs.
=> Consul check documentation improvement

registrator.go
Detect if running on Windows, if so default to the docker namedpipe
=> Add Windows detection

circle.yml
The site seems to not deploy properly due to the working directory being bad somehow.
=> hack: check circle directories

circle.yml
The switch to circleci 2.0 completely broke page builds - amongst other things - as the docker build type doesn't support docker volumes.
Moving to the machine build type allows us to use docker volumes, though we lose the ability to use helper functions.
=> Properly use CircleCI 2.0 for builds

Dockerfile
The multistage build failed with "scratch" as the base image. This is because, based from [here](https://stackoverflow.com/questions/49535379/binary-compiled-in-prestage-doesnt-work-in-scratch-container), scratch is an explicitly empty image. It has no shared object, it has no runtime libraries.
The following error was observed when running registrator in docker.
```standard_init_linux.go:190: exec user process caused "no such file or directory"```
The proposed solution for now is to use alpine:3.7 instead of scratch. This fixes the above problem.
=> Use alpine:3.7 instead of scratch

consul/consul.go, docs/user/services.md
Populates Consul's [ServiceMeta](https://www.consul.io/api/agent/service.html#meta) field with Registrator's [Attr](http://gliderlabs.github.io/registrator/latest/user/services/) so that we can query a service with additional attributes bypassing the need to use a key/value store:
Example:
Setting the following container's environment variables to the following:
- SERVICE_PROTOCOL="http"
- SERVICE_TYPE="service"
would result in: (Note the ServiceMeta field).
```json
[{
"ID": "26596b52-0d61-ee5c-bac2-52d66b8ee8fc",
"Node": "test-node",
"Address": "xxx",
"Datacenter": "eu-west-1",
"TaggedAddresses": {
"lan": "xxx",
"wan": "xxx"
},
"NodeMeta": {
"consul-network-segment": ""
},
"ServiceID": "xxx",
"ServiceName": "users",
"ServiceTags": [
"environment=devel",
"zone=eu-west-1a"
], …
```
=> Populate Consul's ServiceMeta using service.Attrs

Dockerfile, Dockerfile.dev
A quick fix to make `Dockerfile.dev` usable and more or less match `Dockerfile`.
Also, fixes a whitespace formatting issue in `Dockerfile`
=> Fix Dockerfile.dev

.circleci/config.yml, .dockerignore, .gitignore, Dockerfile, Gopkg.lock, Gopkg.toml, consul/consul.go, docs/user/backends.md
This PR resolves the merge conflicts in #568 
Package dependencies that were out of date or old, due to the age of the PR, were removed or replaced in favor of dependencies from master. The dependencies file was also sorted to make maintaining it easier.
I also fixed the unintentional addition of the `vendor/` directory to the branch. This should not be committed to source control, instead allowing `dep ensure -vendor-only` to populate it during a build.
The multi stage build was also revised to properly lock it to a consistent go version (in this case, 1.9.4, which was the default package version for golang at alpine3.7).
Follow-up PRs may wish to further bump the golang version / other packages. This PR is purely to resolve the merge conflicts to allow us to get a build.
=> resolve merge conflicts in PR-568 (update vendor libraries to fix tls support)

consul/consul.go
In upstream Consul (as of May 2018), check.Script has been removed in
favour of check.Args, which now results in the following build error:
consul/consul.go:108:8: check.Script undefined (type *api.AgentServiceCheck has no field or method Script)
consul/consul.go:110:8: check.Script undefined (type *api.AgentServiceCheck has no field or method Script)
consul/consul.go:121:10: check.Script undefined (type *api.AgentServiceCheck has no field or method Script)
Update to use the new convention.
=> Convert from check.Script to check.Args for Consul API changes
